### PR TITLE
Fixed test compatibility

### PR DESCRIPTION
**Pull request by dantleech**
Use expanded class names instead of `::class`.

@WouterJ is this what you meant? I am slghtly confused about the role of the `2.0` branch vs `master`.

### CODE REVIEW

**Comment by dantleech** [comment]
If we are not allowed to use the `::class` syntax, then should add 5.4 to travis again?

**Comment by WouterJ** [comment]
@dantleech this is not precisely what I meant. First, I'll try solve your branch confusion: CmfMenuBundle 2.0 stable is already released (together with CMF 1.3). So master is 2.1 dev now.

CmfMenuBundle 2.0 will be maintained for at least 3 more years. This means that as soon as we change something in a test on 2.0, we'll have merge conflicts to master (as master has been completely refactored).<br>
Also CmfMenuBundle 2.0 requires PHP 5.3.9+, so we can't change them to class constants on master. Only new code in 2.1 is allowed to use PHP 5.4+ features like `::class`.

If we are really desperate to use prophecy instead of PHPunit mocks (I don't exactly know why), we have to do it in the 2.0 branch and merge the changes up to 2.1. This way, we don't have any merge conflicts the coming 3 years.

**Comment by dantleech** [comment]
I see, makes sense.

> If we are really desperate to use prophecy instead of PHPunit mocks 

I just find it significantly easier to work with Prophecy. So if its all
the same I would rather update tests to use it than battle with PHPUnit
mocks.

We can port this back to 2.0 - I also want to test all the exceptions
which is one of the reasons I made this refactoring.

**Comment by dbu** [comment]
i have no problems with moving to prophecy for some of the tests.

**Comment by dbu** [comment]
this is already fixed in the 2.0 branch. i will see about updating master from 2.0

**Pull request closed without merging**
