### PR TITLE
request is unneeded

### PR DESCRIPTION
**Pull request by dbu**
see also https://github.com/symfony/symfony/pull/21662

### CODE REVIEW

**Comment by xabbuh** [comment]
You will want to detect the installed version of the DependencyInjection component and depending on it set the `strict` attribute to `false` (you can, for example, check for the `Symfony\Component\DependencyInjection\ContainerAware` class to be present as it was removed in 3.0).

**Comment by xabbuh** [comment]
By the way, why don't you inject the `request_stack` service instead and drop the method call altogether?

**Comment by dbu** [comment]
> By the way, why don't you inject the |request_stack| service instead and
> drop the method call altogether?

probably because of BC. so now would be the time to change that,
actually. thanks, that was the right question :-)

**Comment by xabbuh** [comment]
Guess so, but now you depend on FrameworkBundle >=2.8 which doesn't allow pre 2.4 versions of the HttpFoundation anyway. :)

**Comment by dbu** [comment]
sudden plot twist: the request seems to never be used. nothing extends this provider, and it does not use $this->request internally and there is no getter. removing, and cleaning up some other things i noticed.

**Pull request merged**
