### PR TITLE
Master dev kit

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
Remove all deprecation warnings and other style stuff in generated files.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
@dbu here i would need your direct influence at symfony con, we need the renderer service to be public and the open PR at knp to be merged at all. :-)

**Comment by ElectricMaxxx** [comment]
@dbu this is the blocker here:

```
Remaining deprecation triggered by Symfony\Cmf\Bundle\MenuBundle\Tests\Functional\RenderingTest::testWithAutomaticLinkType:
The "knp_menu.renderer.twig" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
Stack trace:
#0 vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(275): trigger_error('The "knp_menu.r...', 16384)
#1 vendor/knplabs/knp-menu-bundle/Renderer/ContainerAwareProvider.php(31): Symfony\Component\DependencyInjection\Container->get('knp_menu.render...')
#2 vendor/knplabs/knp-menu/src/Knp/Menu/Twig/Helper.php(94): Knp\Bundle\MenuBundle\Renderer\ContainerAwareProvider->get('twig')
#3 vendor/knplabs/knp-menu/src/Knp/Menu/Twig/MenuExtension.php(75): Knp\Menu\Twig\Helper->render(Object(Knp\Menu\MenuItem), Array, NULL)
#4 tests/Fixtures/App/var/cache/twig/a3/a35d74595c71671b65b5762c6135500a334214d79eef2c30dc05f3af636bc839.php(22): Knp\Menu\Twig\MenuExtension->render('test-menu')
#5 vendor/twig/twig/lib/Twig/Template.php(389): __TwigTemplate_4af04c447b9a82e5eaba2c5ef640dc5b3bbe0bf37589416a796bb764f9f903fb->doDisplay(Array, Array)
#6 vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->displayWithErrorHandling(Array, Array)
#7 vendor/twig/twig/lib/Twig/Template.php(374): Twig_Template->display(Array)
#8 tests/Functional/RenderingTest.php(29): Twig_Template->render(Array)
#9 [internal function]: Symfony\Cmf\Bundle\MenuBundle\Tests\Functional\RenderingTest->testWithAutomaticLinkType()
```
Not sure why the `ContainerAwareProvider` comes in here, but @stof says it won't be supported for Symfony 3.3+ at all, so how to solve that?

**Comment by stof** [comment]
@ElectricMaxxx can you test this against https://github.com/KnpLabs/KnpMenuBundle/pull/358 on KnpMenuBundle ?

**Comment by ElectricMaxxx** [comment]
@stof sorry for asking, but i am to stupid atm to get the branch of your fork:
i added
```
    "repositories": [
        {
            "type": "git",
            "url": "git@github.com:stof/KnpMenuBundle.git"
        }
    ],
```
and required `knplabs/knp-menu:dev-knp_menu_next` But the branch can't be found. What am i doing wrong?

**Comment by stof** [comment]
@ElectricMaxxx this is a branch for the bundle, not for the library

**Comment by ElectricMaxxx** [comment]
@stof got it locally: with your fix the deprecation warnings are gone on symfony 3.4, so it should work now. Thanks a lot.

**Comment by ElectricMaxxx** [comment]
Thanks to @stof  this one is getting green now. Yea.

**Comment by ElectricMaxxx** [comment]
@dbu What do you think, shall i merge?

**Comment by ElectricMaxxx** [comment]
I will merge now, we will have enough chances to change until stable :-)

**Comment by dbu** [comment]
cool, thanks!

**Pull request merged**
