### PR TITLE
moving phpcr-odm and phpcr-bundle into require-dev section

### PR DESCRIPTION
**Pull request by ElectricMaxxx**
the persistence in phpcr should be disabled by default, so this should also work. lets see.

### CODE REVIEW

**Comment by ElectricMaxxx** [comment]
Doing so the `./bin/install.sh -psymfony-cmf/menu-bundle -vdev-fix_installation` call in my `installation-testing` component reduces the error on the error of core-bundle: 
```
Executing script make cache-warmup [KO]
 [KO]
Script make cache-warmup returned with error code 2
!!  
!!  
!!                                                                                   
!!  
!!    [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
!!    The "publish_workflow.request_listener" may not be enabled unless "Symfony\    
!!  
!!    Cmf\Bundle\RoutingBundle\Routing\DynamicRouter" is available.                  
!!  
!!                                                                                   
!!  
!!  
!!  Makefile:15: recipe for target 'cache-clear' failed
!!  
!!  make: *** [cache-clear] Error 1
!!  
!!  
```
which shouldn't have to be required by default as the publisch_workflow isn't enabled by default here.

**Comment by ElectricMaxxx** [comment]
Doing so it is fine from our side i only get: 
```
!!    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
!!    The service "knp_menu.renderer.twig" has a dependency on a non-existent ser  
!!    vice "twig".                                                                 
```
which means `knplabs/knp-menu-bundle` need twig: https://github.com/KnpLabs/KnpMenuBundle/issues/359

**Comment by ElectricMaxxx** [comment]
We should only make the version contraint on knp less restrictive :-)

**Comment by dbu** [comment]
oh, so we do not need the core bundle for the default functionality? that would be nice!

if core bundle is not required, why do you get an error about the core bundle in your tests? looks to me like it should not be installed when you use just the menu bundle in a project.

**Comment by ElectricMaxxx** [comment]
@dbu cause i moved `core-bundle ` later.

**Comment by ElectricMaxxx** [comment]
And yes, now the installation has got the twig issue on knp only.

**Comment by ElectricMaxxx** [comment]
ah i should have waited for the release ... :-)

**Pull request merged**
